### PR TITLE
Add maplibregl module

### PR DESCRIPTION
**Pull request by giswqs**
```python
import leafmap.maplibregl as leafmap
from maplibre.sources import GeoJSONSource

m = leafmap.Map(center=[49.24658, -123.1256], zoom=12, height="600px")

vancouver_blocks = GeoJSONSource(
    data="https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json",
)

layer = Layer(
        type=LayerType.LINE,
        source=vancouver_blocks,
        paint={"line-color": "white"},
    )

m.add_layer(layer)
m
```
image

### CODE REVIEW

**Comment by giswqs** [comment]
```python
import leafmap.maplibregl as leafmap

m = leafmap.Map()
m.add_control("scale", position='bottom-left')
m.add_basemap("OpenTopoMap", show=True)
data="https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json"
m.add_geojson(data, layer_name="Vancouver Blocks", paint={"line-color": "red"})
m.set_center(-123.1256, 49.24658, zoom=12)
m
```
image

**Comment by cboettig** [comment]
this looks really promising!  I was just trying testing out if we could do pmtiles formats, or any of the other types of [sources recognized by maplibre](https://maplibre.org/maplibre-style-spec/sources/#type).  It looks like to maplibre pmtiles merely uses the generic "vector" format.  It looks like there's acknowledgement of each of these source types in the [maplibre python module](https://github.com/eodaGmbH/py-maplibregl/blob/main/maplibre/sources.py#L11), but can't figure out how they are used...  Have you had a chance to look at that?

**Comment by giswqs** [comment]
I have not looked into pmtiles with py-maplibre yet. Currently, there is a blocker the prevents this PR from being merged due to the outdated anywidget version used by py-maplibre, which is incompatible with lonboard. I subbmitted the [PR](https://github.com/eodaGmbH/py-maplibregl/pull/42) last week, but the maintainer has not responded yet.

**Comment by crazycapivara** [comment]
> I have not looked into pmtiles with py-maplibre yet. Currently, there is a blocker the prevents this PR from being merged due to the outdated anywidget version used by py-maplibre, which is incompatible with lonboard. I subbmitted the [PR](https://github.com/eodaGmbH/py-maplibregl/pull/42) last week, but the maintainer has not responded yet.

It is merged setting anywidget to >=0.9.0

**Pull request merged**
