### PR TITLE
Add support for searching NASA data interactively

### PR DESCRIPTION
**Pull request by giswqs**
This PR adds support for searhcing and visualizing NASA Earth data (footprints) interacitvely. 

@BriannaLind @betolink @mfisher87

https://github.com/opengeos/leafmap/assets/5016453/d3683f73-e639-4dcd-be3b-b28937a044ba

### CODE REVIEW

**Comment by mfisher87** [comment]
That's so cool! :star_struck:

**Comment by BriannaLind** [comment]
This looks awesome!  It looks so awesome, it got me thinking - is there a way to pull out coincidental datasets?

**Comment by giswqs** [comment]
What are coincidental datasets?

**Comment by giswqs** [comment]
An updated demo:

https://github.com/opengeos/leafmap/assets/5016453/11ce828a-bda7-476a-bb04-efdd213e08a5

**Comment by BriannaLind** [comment]
Like ones that occur at generally the same time/ date and place...... So for example, it could be like ECOSTRESS, LANDSAT, and VIIRS from the same day and location

**Comment by giswqs** [comment]
Yes, it should be feasible with code. Maybe a bit crowded to have the multi-select option on the GUI

**Comment by betolink** [comment]
For what it's worth, earthaccess will have something like this hopefully soon, see https://github.com/nsidc/earthaccess-gallery/blob/main/notebooks%2Fexplore.ipynb and like @giswqs mentions, it gets a bit crowded for datasets with high temporal coverage.

**Comment by giswqs** [comment]
@betolink That's great to hear. It will make my life much easier if earthaccess can retrieve the footprints directly. 
I just added support visualizing in-memory raster datasets (https://github.com/opengeos/leafmap/pull/651), including numpy.ndarray and xarray.DataArray, paving the way for visualizing NASA Earth data interactively with leafmap.

**Comment by BriannaLind** [comment]
@giswqs @betolink very cool.  Yeah --- so visually I can see it getting crowded; but as a scientist - it is legit crucial to know where data overlaps + and the quality (ie cloud coverage +) so that decisions can be made, and the scope of feasible questions can be assessed.  At this point knowing there is general coverage a data table with some of the quality information would make a world of difference.

**Pull request merged**
