### PR TITLE
Fix add_geojson style callback bug

### PR DESCRIPTION
**Pull request by giswqs**
Fix the bug reported in https://github.com/opengeos/leafmap/issues/119#issuecomment-2365309039

### CODE REVIEW

**Comment by pakrajausama** [comment]
One more question Many thanks for your previous kind response, @giswqs 
Can we add custom markers in png or jpeg to our point-shape file or geojson or csv data?
i have tried a lot but all in vien 
can we add png as marker in this code? 
i have learned on website too but am unable to understand it
--------------
import leafmap
m = leafmap.Map(center=[23, 69], zoom=4) 
shp_path = 'data/point.shp'  
point_style = {            
    'radius': 0.1,              
    'opacity': 1.0           
}
m.add_shp(
    shp_path,
    layer_name='Point Layer',
    style=point_style,         
    info_mode='on_click',
    zoom_to_layer=True       
)
m

**Comment by giswqs** [comment]
See https://leafmap.org/notebooks/50_marker_cluster/

**Comment by pakrajausama** [comment]
thanku soo much...

**Comment by pakrajausama** [comment]
Aslam alikm @giswqs 
I dont know why but after this code there are 2 color ramp in map canvas

----
leafmap version 0.38.0
----
code:

from leafmap import leafmap
m = leafmap.Map(center=[30, 70], zoom=6)
dem = 'data/Dem agropak.tif'
m.add_raster(
    dem,
    colormap="terrain",   
    layer_name='Pak elevation',
    vmin=0,  
    vmax=3000,  
    zoom_to_layer=True,  
   
)
m.add_colormap(
    "terrain",
    label="Elevation",
    width=3.0,
    height=0.2,
    orientation="horizontal",
    vmin=0,
    vmax=3000,
)
m

====
Screenshot 2024-09-23 174249

**Comment by giswqs** [comment]
Restart VS Code

**Pull request merged**
