### PR TITLE
add bounds warning for numpy_to_cog

### LINKED ISSUE #472: bounds warning in numpy_to_cog
If `bounds` are not passed into `numpy_to_cog`, it will be set as a constant global value.

https://github.com/opengeos/leafmap/blob/cf9d594af2859f4059d449842f1ba4bd2797523d/leafmap/common.py#L3754-L3755

This will lead to the wrong profile in COG file. It's better to raise a warning when it's not passed.

### PR DESCRIPTION
**Pull request by zxdawn**
Fix #472

### CODE REVIEW

**Comment by zxdawn** [comment]
I'm not sure why the warning isn't shown ... Maybe this line?

https://github.com/opengeos/leafmap/blob/cf9d594af2859f4059d449842f1ba4bd2797523d/leafmap/common.py#L3729

**Comment by giswqs** [comment]
You can move `warnings.filterwarnings("ignore") ` to after your bounds warning. The reason I added that is because sometimes the conversion process throws a lot of warning messages.

**Comment by zxdawn** [comment]
Strange. Neither deleting nor moving `warnings.filterwarnings("ignore")` works.

**Comment by giswqs** [comment]
Or simply using something like this:

```python
if bounds is None:
    print('warning: bounds is not set. Using the default bounds (-180.0, -85.0511, 180.0, 85.0511)')

**Comment by zxdawn** [comment]
OK, done.

**Comment by giswqs** [comment]
Looks good. Thank you for your contribution.

**Pull request merged**
